# Generated with generate_sources.sh
# find app/ -name test_\*.cpp | sort | sed "s/app\///g" | sed "s/\.cpp/\.cpp \\\/g"
SOURCES += \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/test_buydecision1configwidget.cpp \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/test_buydecision1configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision1config/test_buydecision1config.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/test_buydecision2configwidget.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/test_buydecision2configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision2config/test_buydecision2config.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/test_buydecision3configwidget.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/test_buydecision3configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision3config/test_buydecision3config.cpp \
    src/config/decisions/decisionmakerconfigwidget/test_decisionmakerconfigwidget.cpp \
    src/config/decisions/decisionmakerconfigwidget/test_decisionmakerconfigwidgetfactory.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/test_selldecision1configwidget.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/test_selldecision1configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision1config/test_selldecision1config.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/test_selldecision2configwidget.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/test_selldecision2configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision2config/test_selldecision2config.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/test_selldecision3configwidget.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/test_selldecision3configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision3config/test_selldecision3config.cpp \
    src/config/decisions/test_decisionmakerconfig.cpp \
    src/config/test_config.cpp \
    src/db/instruments/test_instrumentsdatabase.cpp \
    src/db/logs/test_logsdatabase.cpp \
    src/db/operations/test_operationsdatabase.cpp \
    src/db/stocks/test_stocksdatabase.cpp \
    src/db/user/test_userdatabase.cpp \
    src/dialogs/authdialog/test_authdialog.cpp \
    src/dialogs/authdialog/test_authdialogfactory.cpp \
    src/dialogs/orderwavesdialog/test_orderwavesdialog.cpp \
    src/dialogs/orderwavesdialog/test_orderwavesdialogfactory.cpp \
    src/dialogs/settingsdialog/test_settingsdialog.cpp \
    src/dialogs/settingsdialog/test_settingsdialogfactory.cpp \
    src/dialogs/startautopilotdialog/test_startautopilotdialog.cpp \
    src/dialogs/startautopilotdialog/test_startautopilotdialogfactory.cpp \
    src/dialogs/startsimulationdialog/test_startsimulationdialog.cpp \
    src/dialogs/startsimulationdialog/test_startsimulationdialogfactory.cpp \
    src/domain/filter/test_logfilter.cpp \
    src/domain/filter/test_stockfilter.cpp \
    src/domain/instrument/test_instrument.cpp \
    src/domain/log/test_logentry.cpp \
    src/domain/operation/test_operation.cpp \
    src/domain/operation/test_operationfifoitem.cpp \
    src/domain/orderbook/test_orderbook.cpp \
    src/domain/portfolio/test_portfolio.cpp \
    src/domain/portfolio/test_portfolioitem.cpp \
    src/domain/portfolio/test_portfoliominitem.cpp \
    src/domain/quotation/test_quotation.cpp \
    src/domain/stock/test_stock.cpp \
    src/domain/stock/test_stockmeta.cpp \
    src/domain/stock/test_stockoperational.cpp \
    src/domain/trading/test_tradinginfo.cpp \
    src/domain/user/test_account.cpp \
    src/domain/user/test_user.cpp \
    src/grpc/test_grpcclient.cpp \
    src/grpc/test_rawgrpcclient.cpp \
    src/grpc/test_utils.cpp \
    src/main/test_mainwindow.cpp \
    src/storage/instruments/test_instrumentsstorage.cpp \
    src/storage/stocks/test_stocksstorage.cpp \
    src/storage/user/test_userstorage.cpp \
    src/threads/cleanup/test_cleanupthread.cpp \
    src/threads/follow/test_followthread.cpp \
    src/threads/lastprice/test_lastpricethread.cpp \
    src/threads/logs/test_logsthread.cpp \
    src/threads/makedecision/test_makedecisionthread.cpp \
    src/threads/operations/test_operationsthread.cpp \
    src/threads/orderbook/test_orderbookthread.cpp \
    src/threads/parallelhelper/test_parallelhelperthread.cpp \
    src/threads/portfolio/test_portfoliothread.cpp \
    src/threads/portfoliolastprice/test_portfoliolastpricethread.cpp \
    src/threads/pricecollect/test_pricecollectthread.cpp \
    src/threads/trading/test_tradingthread.cpp \
    src/threads/trading/test_tradingthreadfactory.cpp \
    src/threads/userupdate/test_userupdatethread.cpp \
    src/utils/autorunenabler/test_autorunenabler.cpp \
    src/utils/filedialog/test_filedialog.cpp \
    src/utils/filedialog/test_filedialogfactory.cpp \
    src/utils/fs/dir/test_dir.cpp \
    src/utils/fs/dir/test_dirfactory.cpp \
    src/utils/fs/file/test_file.cpp \
    src/utils/fs/file/test_filefactory.cpp \
    src/utils/fs/zip/qzip/test_qzip.cpp \
    src/utils/fs/zip/qzip/test_qzipfactory.cpp \
    src/utils/fs/zip/qzipfile/test_qzipfile.cpp \
    src/utils/fs/zip/qzipfile/test_qzipfilefactory.cpp \
    src/utils/http/test_httpclient.cpp \
    src/utils/logger/test_logger.cpp \
    src/utils/messagebox/test_messageboxutils.cpp \
    src/utils/settingseditor/test_settingseditor.cpp \
    src/utils/style/test_darkpalette.cpp \
    src/utils/timeutils/test_timeutils.cpp \
    src/widgets/accountchartwidget/test_accountchartwidget.cpp \
    src/widgets/accountchartwidget/test_accountchartwidgetfactory.cpp \
    src/widgets/accountchartwidget/test_charttooltip.cpp \
    src/widgets/decisionmakerwidget/test_decisionmakerwidget.cpp \
    src/widgets/decisionmakerwidget/test_decisionmakerwidgetfactory.cpp \
    src/widgets/instrumentwidget/test_instrumentwidget.cpp \
    src/widgets/instrumentwidget/test_instrumentwidgetfactory.cpp \
    src/widgets/logsfilterwidget/test_logsfilterwidget.cpp \
    src/widgets/logsfilterwidget/test_logsfilterwidgetfactory.cpp \
    src/widgets/logstablewidget/test_logstablewidget.cpp \
    src/widgets/logstablewidget/test_logstablewidgetfactory.cpp \
    src/widgets/operationstablewidget/test_operationstablewidget.cpp \
    src/widgets/operationstablewidget/test_operationstablewidgetfactory.cpp \
    src/widgets/orderwaveswidget/test_orderwaveswidget.cpp \
    src/widgets/orderwaveswidget/test_orderwaveswidgetfactory.cpp \
    src/widgets/portfoliotreewidget/test_portfoliotreewidget.cpp \
    src/widgets/portfoliotreewidget/test_portfoliotreewidgetfactory.cpp \
    src/widgets/stockscontrolswidget/test_stockscontrolswidget.cpp \
    src/widgets/stockscontrolswidget/test_stockscontrolswidgetfactory.cpp \
    src/widgets/stockstablewidget/test_stockstablewidget.cpp \
    src/widgets/stockstablewidget/test_stockstablewidgetfactory.cpp \
    src/widgets/tableitems/actions/test_actionstableitemwidget.cpp \
    src/widgets/tableitems/actions/test_actionstableitemwidgetfactory.cpp \
    src/widgets/tableitems/instrument/test_instrumenttableitemwidget.cpp \
    src/widgets/tableitems/instrument/test_instrumenttableitemwidgetfactory.cpp \
    src/widgets/tableitems/loglevel/test_logleveltableitemwidget.cpp \
    src/widgets/tableitems/loglevel/test_logleveltableitemwidgetfactory.cpp \
    src/widgets/tableitems/test_integertableitem.cpp \
    src/widgets/tableitems/test_moneychangepercenttableitem.cpp \
    src/widgets/tableitems/test_moneychangetableitem.cpp \
    src/widgets/tableitems/test_moneytableitem.cpp \
    src/widgets/tableitems/test_paybacktableitem.cpp \
    src/widgets/tableitems/test_timetableitem.cpp \
    src/widgets/tableitems/test_turnovertableitem.cpp \
    src/widgets/tablerecords/logstablerecord/test_logstablerecord.cpp \
    src/widgets/tablerecords/logstablerecord/test_logstablerecordfactory.cpp \
    src/widgets/tablerecords/operationstablerecord/test_operationstablerecord.cpp \
    src/widgets/tablerecords/operationstablerecord/test_operationstablerecordfactory.cpp \
    src/widgets/tablerecords/stockstablerecord/test_stockstablerecord.cpp \
    src/widgets/tablerecords/stockstablerecord/test_stockstablerecordfactory.cpp \
    src/widgets/trayicon/test_trayicon.cpp \
    src/widgets/trayicon/test_trayiconfactory.cpp \
    src/widgets/treeitems/test_categorytreeitem.cpp \
    src/widgets/treeitems/test_portfoliotreeitem.cpp \
    src/widgets/treerecords/portfoliotreerecord/test_portfoliotreerecord.cpp \
    src/widgets/treerecords/portfoliotreerecord/test_portfoliotreerecordfactory.cpp \

# find app/ -name \*_mock.h | sort | sed "s/app\///g" | sed "s/\.h/\.h \\\/g"
HEADERS += \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidget_mock.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision1config/ibuydecision1config_mock.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidget_mock.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision2config/ibuydecision2config_mock.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidget_mock.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision3config/ibuydecision3config_mock.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidget_mock.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidgetfactory_mock.h \
    src/config/decisions/idecisionmakerconfig_mock.h \
    src/config/decisions/sell/selldecision1config/iselldecision1config_mock.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidget_mock.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidgetfactory_mock.h \
    src/config/decisions/sell/selldecision2config/iselldecision2config_mock.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidget_mock.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidgetfactory_mock.h \
    src/config/decisions/sell/selldecision3config/iselldecision3config_mock.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidget_mock.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidgetfactory_mock.h \
    src/config/iconfig_mock.h \
    src/db/instruments/iinstrumentsdatabase_mock.h \
    src/db/logs/ilogsdatabase_mock.h \
    src/db/operations/ioperationsdatabase_mock.h \
    src/db/stocks/istocksdatabase_mock.h \
    src/db/user/iuserdatabase_mock.h \
    src/dialogs/authdialog/iauthdialog_mock.h \
    src/dialogs/authdialog/iauthdialogfactory_mock.h \
    src/dialogs/orderwavesdialog/iorderwavesdialog_mock.h \
    src/dialogs/orderwavesdialog/iorderwavesdialogfactory_mock.h \
    src/dialogs/settingsdialog/isettingsdialog_mock.h \
    src/dialogs/settingsdialog/isettingsdialogfactory_mock.h \
    src/dialogs/startautopilotdialog/istartautopilotdialog_mock.h \
    src/dialogs/startautopilotdialog/istartautopilotdialogfactory_mock.h \
    src/dialogs/startsimulationdialog/istartsimulationdialog_mock.h \
    src/dialogs/startsimulationdialog/istartsimulationdialogfactory_mock.h \
    src/grpc/igrpcclient_mock.h \
    src/grpc/irawgrpcclient_mock.h \
    src/storage/instruments/iinstrumentsstorage_mock.h \
    src/storage/stocks/istocksstorage_mock.h \
    src/storage/user/iuserstorage_mock.h \
    src/threads/cleanup/icleanupthread_mock.h \
    src/threads/follow/ifollowthread_mock.h \
    src/threads/lastprice/ilastpricethread_mock.h \
    src/threads/logs/ilogsthread_mock.h \
    src/threads/makedecision/imakedecisionthread_mock.h \
    src/threads/operations/ioperationsthread_mock.h \
    src/threads/orderbook/iorderbookthread_mock.h \
    src/threads/portfolio/iportfoliothread_mock.h \
    src/threads/portfoliolastprice/iportfoliolastpricethread_mock.h \
    src/threads/pricecollect/ipricecollectthread_mock.h \
    src/threads/trading/itradingthread_mock.h \
    src/threads/trading/itradingthreadfactory_mock.h \
    src/threads/userupdate/iuserupdatethread_mock.h \
    src/utils/autorunenabler/iautorunenabler_mock.h \
    src/utils/filedialog/ifiledialog_mock.h \
    src/utils/filedialog/ifiledialogfactory_mock.h \
    src/utils/fs/dir/idir_mock.h \
    src/utils/fs/dir/idirfactory_mock.h \
    src/utils/fs/file/ifile_mock.h \
    src/utils/fs/file/ifilefactory_mock.h \
    src/utils/fs/zip/qzip/iqzip_mock.h \
    src/utils/fs/zip/qzip/iqzipfactory_mock.h \
    src/utils/fs/zip/qzipfile/iqzipfile_mock.h \
    src/utils/fs/zip/qzipfile/iqzipfilefactory_mock.h \
    src/utils/http/ihttpclient_mock.h \
    src/utils/messagebox/imessageboxutils_mock.h \
    src/utils/settingseditor/isettingseditor_mock.h \
    src/utils/timeutils/itimeutils_mock.h \
    src/widgets/accountchartwidget/iaccountchartwidget_mock.h \
    src/widgets/accountchartwidget/iaccountchartwidgetfactory_mock.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidget_mock.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidgetfactory_mock.h \
    src/widgets/instrumentwidget/iinstrumentwidget_mock.h \
    src/widgets/instrumentwidget/iinstrumentwidgetfactory_mock.h \
    src/widgets/logsfilterwidget/ilogsfilterwidget_mock.h \
    src/widgets/logsfilterwidget/ilogsfilterwidgetfactory_mock.h \
    src/widgets/logstablewidget/ilogstablewidget_mock.h \
    src/widgets/logstablewidget/ilogstablewidgetfactory_mock.h \
    src/widgets/operationstablewidget/ioperationstablewidget_mock.h \
    src/widgets/operationstablewidget/ioperationstablewidgetfactory_mock.h \
    src/widgets/orderwaveswidget/iorderwaveswidget_mock.h \
    src/widgets/orderwaveswidget/iorderwaveswidgetfactory_mock.h \
    src/widgets/portfoliotreewidget/iportfoliotreewidget_mock.h \
    src/widgets/portfoliotreewidget/iportfoliotreewidgetfactory_mock.h \
    src/widgets/stockscontrolswidget/istockscontrolswidget_mock.h \
    src/widgets/stockscontrolswidget/istockscontrolswidgetfactory_mock.h \
    src/widgets/stockstablewidget/istockstablewidget_mock.h \
    src/widgets/stockstablewidget/istockstablewidgetfactory_mock.h \
    src/widgets/tableitems/actions/iactionstableitemwidget_mock.h \
    src/widgets/tableitems/actions/iactionstableitemwidgetfactory_mock.h \
    src/widgets/tableitems/instrument/iinstrumenttableitemwidget_mock.h \
    src/widgets/tableitems/instrument/iinstrumenttableitemwidgetfactory_mock.h \
    src/widgets/tableitems/loglevel/ilogleveltableitemwidget_mock.h \
    src/widgets/tableitems/loglevel/ilogleveltableitemwidgetfactory_mock.h \
    src/widgets/tablerecords/logstablerecord/ilogstablerecord_mock.h \
    src/widgets/tablerecords/logstablerecord/ilogstablerecordfactory_mock.h \
    src/widgets/tablerecords/operationstablerecord/ioperationstablerecord_mock.h \
    src/widgets/tablerecords/operationstablerecord/ioperationstablerecordfactory_mock.h \
    src/widgets/tablerecords/stockstablerecord/istockstablerecord_mock.h \
    src/widgets/tablerecords/stockstablerecord/istockstablerecordfactory_mock.h \
    src/widgets/trayicon/itrayicon_mock.h \
    src/widgets/trayicon/itrayiconfactory_mock.h \
    src/widgets/treerecords/portfoliotreerecord/iportfoliotreerecord_mock.h \
    src/widgets/treerecords/portfoliotreerecord/iportfoliotreerecordfactory_mock.h \
