# Generated with generate_sources.sh
# find app/ -name test_\*.cpp | sed "s/app\///g" | sed "s/\.cpp/\.cpp \\\/g"
SOURCES += \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/test_buydecision1configwidget.cpp \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/test_buydecision1configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision1config/test_buydecision1config.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/test_buydecision2configwidget.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/test_buydecision2configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision2config/test_buydecision2config.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/test_buydecision3configwidget.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/test_buydecision3configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision3config/test_buydecision3config.cpp \
    src/config/decisions/decisionmakerconfigwidget/test_decisionmakerconfigwidget.cpp \
    src/config/decisions/decisionmakerconfigwidget/test_decisionmakerconfigwidgetfactory.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/test_selldecision1configwidget.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/test_selldecision1configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision1config/test_selldecision1config.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/test_selldecision2configwidget.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/test_selldecision2configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision2config/test_selldecision2config.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/test_selldecision3configwidget.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/test_selldecision3configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision3config/test_selldecision3config.cpp \
    src/config/decisions/test_decisionmakerconfig.cpp \
    src/config/test_config.cpp \
    src/db/stocks/test_stocksdatabase.cpp \
    src/db/user/test_userdatabase.cpp \
    src/dialogs/authdialog/test_authdialog.cpp \
    src/dialogs/authdialog/test_authdialogfactory.cpp \
    src/dialogs/orderwavesdialog/test_orderwavesdialog.cpp \
    src/dialogs/orderwavesdialog/test_orderwavesdialogfactory.cpp \
    src/dialogs/settingsdialog/test_settingsdialog.cpp \
    src/dialogs/settingsdialog/test_settingsdialogfactory.cpp \
    src/domain/filter/test_filter.cpp \
    src/domain/orderbook/test_orderbook.cpp \
    src/domain/quotation/test_quotation.cpp \
    src/domain/stocks/test_stock.cpp \
    src/domain/stocks/test_stockmeta.cpp \
    src/domain/stocks/test_stockoperational.cpp \
    src/domain/user/test_account.cpp \
    src/domain/user/test_user.cpp \
    src/grpc/test_grpcclient.cpp \
    src/grpc/test_rawgrpcclient.cpp \
    src/grpc/test_utils.cpp \
    src/main/test_mainwindow.cpp \
    src/storage/stocks/test_stocksstorage.cpp \
    src/storage/user/test_userstorage.cpp \
    src/threads/cleanup/test_cleanupthread.cpp \
    src/threads/lastprice/test_lastpricethread.cpp \
    src/threads/makedecision/test_makedecisionthread.cpp \
    src/threads/orderbook/test_orderbookthread.cpp \
    src/threads/parallelhelper/test_parallelhelperthread.cpp \
    src/threads/pricecollect/test_pricecollectthread.cpp \
    src/threads/userupdate/test_userupdatethread.cpp \
    src/utils/fs/dir/test_dir.cpp \
    src/utils/fs/dir/test_dirfactory.cpp \
    src/utils/fs/file/test_file.cpp \
    src/utils/fs/file/test_filefactory.cpp \
    src/utils/fs/zip/qzip/test_qzip.cpp \
    src/utils/fs/zip/qzip/test_qzipfactory.cpp \
    src/utils/fs/zip/qzipfile/test_qzipfile.cpp \
    src/utils/fs/zip/qzipfile/test_qzipfilefactory.cpp \
    src/utils/http/test_httpclient.cpp \
    src/utils/logger/test_logger.cpp \
    src/utils/messagebox/test_messagebox.cpp \
    src/utils/settingseditor/test_settingseditor.cpp \
    src/utils/style/test_darkpalette.cpp \
    src/utils/timeutils/test_timeutils.cpp \
    src/widgets/decisionmakerwidget/test_decisionmakerwidget.cpp \
    src/widgets/decisionmakerwidget/test_decisionmakerwidgetfactory.cpp \
    src/widgets/filterwidget/test_filterwidget.cpp \
    src/widgets/filterwidget/test_filterwidgetfactory.cpp \
    src/widgets/orderwaveswidget/test_orderwaveswidget.cpp \
    src/widgets/orderwaveswidget/test_orderwaveswidgetfactory.cpp \
    src/widgets/tablerecord/items/actions/test_actionstableitemwidget.cpp \
    src/widgets/tablerecord/items/actions/test_actionstableitemwidgetfactory.cpp \
    src/widgets/tablerecord/items/stock/test_stocktableitemwidget.cpp \
    src/widgets/tablerecord/items/stock/test_stocktableitemwidgetfactory.cpp \
    src/widgets/tablerecord/items/test_paybacktableitem.cpp \
    src/widgets/tablerecord/items/test_pricechangetableitem.cpp \
    src/widgets/tablerecord/items/test_pricetableitem.cpp \
    src/widgets/tablerecord/items/test_turnovertableitem.cpp \
    src/widgets/tablerecord/test_tablerecord.cpp \
    src/widgets/tablerecord/test_tablerecordfactory.cpp \
    src/widgets/trayicon/test_trayicon.cpp \
    src/widgets/trayicon/test_trayiconfactory.cpp \

# find app/ -name \*_mock.h | sed "s/app\///g" | sed "s/\.h/\.h \\\/g"
HEADERS += \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidget_mock.h \
    src/config/decisions/buy/buydecision1config/ibuydecision1config_mock.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidget_mock.h \
    src/config/decisions/buy/buydecision2config/ibuydecision2config_mock.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidgetfactory_mock.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidget_mock.h \
    src/config/decisions/buy/buydecision3config/ibuydecision3config_mock.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidgetfactory_mock.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidget_mock.h \
    src/config/decisions/idecisionmakerconfig_mock.h \
    src/config/decisions/sell/selldecision1config/iselldecision1config_mock.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidgetfactory_mock.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidget_mock.h \
    src/config/decisions/sell/selldecision2config/iselldecision2config_mock.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidgetfactory_mock.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidget_mock.h \
    src/config/decisions/sell/selldecision3config/iselldecision3config_mock.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidgetfactory_mock.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidget_mock.h \
    src/config/iconfig_mock.h \
    src/db/stocks/istocksdatabase_mock.h \
    src/db/user/iuserdatabase_mock.h \
    src/dialogs/authdialog/iauthdialogfactory_mock.h \
    src/dialogs/authdialog/iauthdialog_mock.h \
    src/dialogs/orderwavesdialog/iorderwavesdialogfactory_mock.h \
    src/dialogs/orderwavesdialog/iorderwavesdialog_mock.h \
    src/dialogs/settingsdialog/isettingsdialogfactory_mock.h \
    src/dialogs/settingsdialog/isettingsdialog_mock.h \
    src/grpc/igrpcclient_mock.h \
    src/grpc/irawgrpcclient_mock.h \
    src/storage/stocks/istocksstorage_mock.h \
    src/storage/user/iuserstorage_mock.h \
    src/threads/cleanup/icleanupthread_mock.h \
    src/threads/lastprice/ilastpricethread_mock.h \
    src/threads/makedecision/imakedecisionthread_mock.h \
    src/threads/orderbook/iorderbookthread_mock.h \
    src/threads/pricecollect/ipricecollectthread_mock.h \
    src/threads/userupdate/iuserupdatethread_mock.h \
    src/utils/fs/dir/idirfactory_mock.h \
    src/utils/fs/dir/idir_mock.h \
    src/utils/fs/file/ifilefactory_mock.h \
    src/utils/fs/file/ifile_mock.h \
    src/utils/fs/zip/qzip/iqzipfactory_mock.h \
    src/utils/fs/zip/qzip/iqzip_mock.h \
    src/utils/fs/zip/qzipfile/iqzipfilefactory_mock.h \
    src/utils/fs/zip/qzipfile/iqzipfile_mock.h \
    src/utils/http/ihttpclient_mock.h \
    src/utils/messagebox/imessagebox_mock.h \
    src/utils/settingseditor/isettingseditor_mock.h \
    src/utils/timeutils/itimeutils_mock.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidgetfactory_mock.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidget_mock.h \
    src/widgets/filterwidget/ifilterwidgetfactory_mock.h \
    src/widgets/filterwidget/ifilterwidget_mock.h \
    src/widgets/orderwaveswidget/iorderwaveswidgetfactory_mock.h \
    src/widgets/orderwaveswidget/iorderwaveswidget_mock.h \
    src/widgets/tablerecord/itablerecordfactory_mock.h \
    src/widgets/tablerecord/itablerecord_mock.h \
    src/widgets/tablerecord/items/actions/iactionstableitemwidgetfactory_mock.h \
    src/widgets/tablerecord/items/actions/iactionstableitemwidget_mock.h \
    src/widgets/tablerecord/items/stock/istocktableitemwidgetfactory_mock.h \
    src/widgets/tablerecord/items/stock/istocktableitemwidget_mock.h \
    src/widgets/trayicon/itrayiconfactory_mock.h \
    src/widgets/trayicon/itrayicon_mock.h \
