name: env-vcpkg
description: Environment vcpkg
runs:
  using: "composite"
  steps:
    # Download/upload cache
    - name: Caching
      id: cache-env
      uses: actions/cache@v5
      with:
        path: ./Qt
        key: ${{ runner.os }}-env-vcpkg-${{ env.VCPKG_VERSION }}

    # Checkout vcpkg repository with specific version to $GITHUB_WORKSPACE/vcpkg-source
    - name: Checkout vcpkg
      if: steps.cache-env.outputs.cache-hit != 'true'
      uses: actions/checkout@v6
      with:
        repository: microsoft/vcpkg
        path: vcpkg-source
        ref: ${{ env.VCPKG_VERSION }}

    # Build grpc with specified version
    - name: Build grpc
      if: steps.cache-env.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        # Enter to vcpkg-source folder
        Set-Location -Path "vcpkg-source"

        switch ("${{ runner.os }}")
        {
            "Windows" {
                ./bootstrap-vcpkg.bat
            }
            "Linux" {
                ./bootstrap-vcpkg.sh
            }
        }

        ./vcpkg integrate install
        ./vcpkg install grpc

        # Cleanup
        switch ("${{ runner.os }}")
        {
            "Windows" {
                ${PACKAGE_NAME} = "x64-windows"
                Remove-Item "installed/${PACKAGE_NAME}/debug/bin/*.pdb" -Force
                Remove-Item "installed/${PACKAGE_NAME}/bin/*.pdb" -Force
                Remove-Item "installed/${PACKAGE_NAME}/Program Files" -Recurse -Force
            }
            "Linux" {
                ${PACKAGE_NAME} = "x64-linux"
                Remove-Item "installed/${PACKAGE_NAME}/etc" -Recurse -Force
            }
        }

        Remove-Item "buildtrees" -Recurse -Force
        Remove-Item "installed/vcpkg" -Recurse -Force
        Remove-Item "installed/${PACKAGE_NAME}/debug/lib/pkgconfig" -Recurse -Force
        Remove-Item "installed/${PACKAGE_NAME}/lib/pkgconfig" -Recurse -Force
        Remove-Item "installed/${PACKAGE_NAME}/share" -Recurse -Force

        Copy-Item installed -Destination "${Env:GITHUB_WORKSPACE}/Qt/vcpkg/installed" -Recurse

    # Upload environment artifacts
    - name: Upload environment artifacts
      uses: thebrowsercompany/gha-upload-tar-artifact@main
      with:
        name: env-vcpkg-${{ matrix.config.name }}
        path: ./Qt
        retention-days: 1
