# Generated with generate_sources.sh
VPATH += $${PWD}
INCLUDEPATH += $${PWD}



# find app/ -name \*.cpp | sort | grep -ve test_ -ve app/src/main.cpp | sed "s/app\///g" | sed "s/\.cpp/\.cpp \\\/g"
SOURCES += \
    src/config/config.cpp \
    src/config/decisions/buy/buydecision1config/buydecision1config.cpp \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/buydecision1configwidget.cpp \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/buydecision1configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2config.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/buydecision2configwidget.cpp \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/buydecision2configwidgetfactory.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3config.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/buydecision3configwidget.cpp \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/buydecision3configwidgetfactory.cpp \
    src/config/decisions/decisionmakerconfig.cpp \
    src/config/decisions/decisionmakerconfigwidget/decisionmakerconfigwidget.cpp \
    src/config/decisions/decisionmakerconfigwidget/decisionmakerconfigwidgetfactory.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1config.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/selldecision1configwidget.cpp \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/selldecision1configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2config.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/selldecision2configwidget.cpp \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/selldecision2configwidgetfactory.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3config.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/selldecision3configwidget.cpp \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/selldecision3configwidgetfactory.cpp \
    src/db/instruments/instrumentsdatabase.cpp \
    src/db/logos/logosdatabase.cpp \
    src/db/logs/logsdatabase.cpp \
    src/db/operations/operationsdatabase.cpp \
    src/db/stocks/stocksdatabase.cpp \
    src/db/user/userdatabase.cpp \
    src/dialogs/authdialog/authdialog.cpp \
    src/dialogs/authdialog/authdialogfactory.cpp \
    src/dialogs/orderwavesdialog/orderwavesdialog.cpp \
    src/dialogs/orderwavesdialog/orderwavesdialogfactory.cpp \
    src/dialogs/settingsdialog/settingsdialog.cpp \
    src/dialogs/settingsdialog/settingsdialogfactory.cpp \
    src/dialogs/startautopilotdialog/startautopilotdialog.cpp \
    src/dialogs/startautopilotdialog/startautopilotdialogfactory.cpp \
    src/dialogs/startsimulationdialog/startsimulationdialog.cpp \
    src/dialogs/startsimulationdialog/startsimulationdialogfactory.cpp \
    src/domain/filter/logfilter.cpp \
    src/domain/filter/stockfilter.cpp \
    src/domain/instrument/instrument.cpp \
    src/domain/log/logentry.cpp \
    src/domain/operation/operation.cpp \
    src/domain/operation/operationfifoitem.cpp \
    src/domain/orderbook/orderbook.cpp \
    src/domain/portfolio/portfolio.cpp \
    src/domain/portfolio/portfoliocategoryitem.cpp \
    src/domain/portfolio/portfolioitem.cpp \
    src/domain/portfolio/portfoliominitem.cpp \
    src/domain/quotation/quotation.cpp \
    src/domain/stock/stock.cpp \
    src/domain/stock/stockmeta.cpp \
    src/domain/stock/stockoperational.cpp \
    src/domain/stock/stocktableentry.cpp \
    src/domain/trading/tradinginfo.cpp \
    src/domain/user/account.cpp \
    src/domain/user/user.cpp \
    src/grpc/grpcclient.cpp \
    src/grpc/rawgrpcclient.cpp \
    src/grpc/utils.cpp \
    src/main/mainwindow.cpp \
    src/storage/instruments/instrumentsstorage.cpp \
    src/storage/logos/logosstorage.cpp \
    src/storage/stocks/stocksstorage.cpp \
    src/storage/user/userstorage.cpp \
    src/threads/cleanup/cleanupthread.cpp \
    src/threads/follow/followthread.cpp \
    src/threads/lastprice/lastpricethread.cpp \
    src/threads/logs/logsthread.cpp \
    src/threads/makedecision/makedecisionthread.cpp \
    src/threads/operations/operationsthread.cpp \
    src/threads/orderbook/orderbookthread.cpp \
    src/threads/portfolio/portfoliothread.cpp \
    src/threads/portfoliolastprice/portfoliolastpricethread.cpp \
    src/threads/pricecollect/pricecollectthread.cpp \
    src/threads/trading/tradingthread.cpp \
    src/threads/trading/tradingthreadfactory.cpp \
    src/threads/userupdate/userupdatethread.cpp \
    src/utils/autorunenabler/autorunenabler.cpp \
    src/utils/filedialog/filedialog.cpp \
    src/utils/filedialog/filedialogfactory.cpp \
    src/utils/fs/dir/dir.cpp \
    src/utils/fs/dir/dirfactory.cpp \
    src/utils/fs/file/file.cpp \
    src/utils/fs/file/filefactory.cpp \
    src/utils/fs/zip/qzip/qzip.cpp \
    src/utils/fs/zip/qzip/qzipfactory.cpp \
    src/utils/fs/zip/qzipfile/qzipfile.cpp \
    src/utils/fs/zip/qzipfile/qzipfilefactory.cpp \
    src/utils/http/httpclient.cpp \
    src/utils/logger/logger.cpp \
    src/utils/messagebox/messageboxutils.cpp \
    src/utils/settingseditor/settingseditor.cpp \
    src/utils/style/darkpalette.cpp \
    src/utils/timeutils/timeutils.cpp \
    src/widgets/accountchartwidget/accountchartwidget.cpp \
    src/widgets/accountchartwidget/accountchartwidgetfactory.cpp \
    src/widgets/accountchartwidget/charttooltip.cpp \
    src/widgets/actionstableitemwidget/actionstableitemwidget.cpp \
    src/widgets/actionstableitemwidget/actionstableitemwidgetfactory.cpp \
    src/widgets/decisionmakerwidget/decisionmakerwidget.cpp \
    src/widgets/decisionmakerwidget/decisionmakerwidgetfactory.cpp \
    src/widgets/logsfilterwidget/logsfilterwidget.cpp \
    src/widgets/logsfilterwidget/logsfilterwidgetfactory.cpp \
    src/widgets/logstablewidget/logstablewidget.cpp \
    src/widgets/logstablewidget/logstablewidgetfactory.cpp \
    src/widgets/operationstablewidget/operationstablewidget.cpp \
    src/widgets/operationstablewidget/operationstablewidgetfactory.cpp \
    src/widgets/orderwaveswidget/orderwaveswidget.cpp \
    src/widgets/orderwaveswidget/orderwaveswidgetfactory.cpp \
    src/widgets/portfoliotreewidget/portfoliotreewidget.cpp \
    src/widgets/portfoliotreewidget/portfoliotreewidgetfactory.cpp \
    src/widgets/stockscontrolswidget/stockscontrolswidget.cpp \
    src/widgets/stockscontrolswidget/stockscontrolswidgetfactory.cpp \
    src/widgets/stockstablewidget/stockstablewidget.cpp \
    src/widgets/stockstablewidget/stockstablewidgetfactory.cpp \
    src/widgets/tabledelegates/instrumentitemdelegate.cpp \
    src/widgets/tabledelegates/loglevelitemdelegate.cpp \
    src/widgets/tablemodels/logstablemodel/logstablemodel.cpp \
    src/widgets/tablemodels/logstablemodel/logstablemodelfactory.cpp \
    src/widgets/tablemodels/operationstablemodel/operationstablemodel.cpp \
    src/widgets/tablemodels/operationstablemodel/operationstablemodelfactory.cpp \
    src/widgets/tablemodels/portfoliotreemodel/portfoliotreemodel.cpp \
    src/widgets/tablemodels/portfoliotreemodel/portfoliotreemodelfactory.cpp \
    src/widgets/tablemodels/stockstablemodel/stockstablemodel.cpp \
    src/widgets/tablemodels/stockstablemodel/stockstablemodelfactory.cpp \
    src/widgets/trayicon/trayicon.cpp \
    src/widgets/trayicon/trayiconfactory.cpp \

# find app/ -name \*.h | sort | grep -ve _mock.h | sed "s/app\///g" | sed "s/\.h/\.h \\\/g"
HEADERS += \
    src/config/config.h \
    src/config/decisions/buy/buydecision1config/buydecision1config.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/buydecision1configwidget.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/buydecision1configwidgetfactory.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidget.h \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/ibuydecision1configwidgetfactory.h \
    src/config/decisions/buy/buydecision1config/ibuydecision1config.h \
    src/config/decisions/buy/buydecision2config/buydecision2config.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/buydecision2configwidget.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/buydecision2configwidgetfactory.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidget.h \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/ibuydecision2configwidgetfactory.h \
    src/config/decisions/buy/buydecision2config/ibuydecision2config.h \
    src/config/decisions/buy/buydecision3config/buydecision3config.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/buydecision3configwidget.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/buydecision3configwidgetfactory.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidget.h \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/ibuydecision3configwidgetfactory.h \
    src/config/decisions/buy/buydecision3config/ibuydecision3config.h \
    src/config/decisions/decisionmakerconfig.h \
    src/config/decisions/decisionmakerconfigwidget/decisionmakerconfigwidget.h \
    src/config/decisions/decisionmakerconfigwidget/decisionmakerconfigwidgetfactory.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidget.h \
    src/config/decisions/decisionmakerconfigwidget/idecisionmakerconfigwidgetfactory.h \
    src/config/decisions/idecisionmakerconfig.h \
    src/config/decisions/sell/selldecision1config/iselldecision1config.h \
    src/config/decisions/sell/selldecision1config/selldecision1config.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidget.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/iselldecision1configwidgetfactory.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/selldecision1configwidget.h \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/selldecision1configwidgetfactory.h \
    src/config/decisions/sell/selldecision2config/iselldecision2config.h \
    src/config/decisions/sell/selldecision2config/selldecision2config.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidget.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/iselldecision2configwidgetfactory.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/selldecision2configwidget.h \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/selldecision2configwidgetfactory.h \
    src/config/decisions/sell/selldecision3config/iselldecision3config.h \
    src/config/decisions/sell/selldecision3config/selldecision3config.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidget.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/iselldecision3configwidgetfactory.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/selldecision3configwidget.h \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/selldecision3configwidgetfactory.h \
    src/config/iconfig.h \
    src/db/instruments/iinstrumentsdatabase.h \
    src/db/instruments/instrumentsdatabase.h \
    src/db/logos/ilogosdatabase.h \
    src/db/logos/logosdatabase.h \
    src/db/logs/ilogsdatabase.h \
    src/db/logs/logsdatabase.h \
    src/db/operations/ioperationsdatabase.h \
    src/db/operations/operationsdatabase.h \
    src/db/stocks/istocksdatabase.h \
    src/db/stocks/stocksdatabase.h \
    src/db/user/iuserdatabase.h \
    src/db/user/userdatabase.h \
    src/dialogs/authdialog/authdialog.h \
    src/dialogs/authdialog/authdialogfactory.h \
    src/dialogs/authdialog/iauthdialog.h \
    src/dialogs/authdialog/iauthdialogfactory.h \
    src/dialogs/orderwavesdialog/iorderwavesdialog.h \
    src/dialogs/orderwavesdialog/iorderwavesdialogfactory.h \
    src/dialogs/orderwavesdialog/orderwavesdialog.h \
    src/dialogs/orderwavesdialog/orderwavesdialogfactory.h \
    src/dialogs/settingsdialog/isettingsdialog.h \
    src/dialogs/settingsdialog/isettingsdialogfactory.h \
    src/dialogs/settingsdialog/settingsdialog.h \
    src/dialogs/settingsdialog/settingsdialogfactory.h \
    src/dialogs/startautopilotdialog/istartautopilotdialog.h \
    src/dialogs/startautopilotdialog/istartautopilotdialogfactory.h \
    src/dialogs/startautopilotdialog/startautopilotdialog.h \
    src/dialogs/startautopilotdialog/startautopilotdialogfactory.h \
    src/dialogs/startsimulationdialog/istartsimulationdialog.h \
    src/dialogs/startsimulationdialog/istartsimulationdialogfactory.h \
    src/dialogs/startsimulationdialog/startsimulationdialog.h \
    src/dialogs/startsimulationdialog/startsimulationdialogfactory.h \
    src/domain/filter/logfilter.h \
    src/domain/filter/stockfilter.h \
    src/domain/instrument/instrument.h \
    src/domain/log/logentry.h \
    src/domain/logo/logo.h \
    src/domain/operation/operation.h \
    src/domain/operation/operationfifoitem.h \
    src/domain/orderbook/orderbook.h \
    src/domain/orderbook/orderbookdata.h \
    src/domain/portfolio/portfolio.h \
    src/domain/portfolio/portfoliocategoryitem.h \
    src/domain/portfolio/portfolioitem.h \
    src/domain/portfolio/portfoliominitem.h \
    src/domain/quotation/quotation.h \
    src/domain/stock/stock.h \
    src/domain/stock/stockdata.h \
    src/domain/stock/stockmeta.h \
    src/domain/stock/stockoperational.h \
    src/domain/stock/stocktableentry.h \
    src/domain/trading/tradinginfo.h \
    src/domain/user/account.h \
    src/domain/user/user.h \
    src/grpc/grpcclient.h \
    src/grpc/igrpcclient.h \
    src/grpc/investapiuthenticator.h \
    src/grpc/irawgrpcclient.h \
    src/grpc/rawgrpcclient.h \
    src/grpc/utils.h \
    src/main/mainwindow.h \
    src/storage/instruments/iinstrumentsstorage.h \
    src/storage/instruments/instrumentsstorage.h \
    src/storage/logos/ilogosstorage.h \
    src/storage/logos/logosstorage.h \
    src/storage/stocks/istocksstorage.h \
    src/storage/stocks/stocksstorage.h \
    src/storage/user/iuserstorage.h \
    src/storage/user/userstorage.h \
    src/threads/cleanup/cleanupthread.h \
    src/threads/cleanup/icleanupthread.h \
    src/threads/follow/followthread.h \
    src/threads/follow/ifollowthread.h \
    src/threads/lastprice/ilastpricethread.h \
    src/threads/lastprice/lastpricethread.h \
    src/threads/logs/ilogsthread.h \
    src/threads/logs/logsthread.h \
    src/threads/makedecision/imakedecisionthread.h \
    src/threads/makedecision/makedecisionthread.h \
    src/threads/operations/ioperationsthread.h \
    src/threads/operations/operationsthread.h \
    src/threads/orderbook/iorderbookthread.h \
    src/threads/orderbook/orderbookthread.h \
    src/threads/parallelhelper/parallelhelperthread.h \
    src/threads/portfolio/iportfoliothread.h \
    src/threads/portfolio/portfoliothread.h \
    src/threads/portfoliolastprice/iportfoliolastpricethread.h \
    src/threads/portfoliolastprice/portfoliolastpricethread.h \
    src/threads/pricecollect/ipricecollectthread.h \
    src/threads/pricecollect/pricecollectthread.h \
    src/threads/trading/itradingthread.h \
    src/threads/trading/itradingthreadfactory.h \
    src/threads/trading/tradingthread.h \
    src/threads/trading/tradingthreadfactory.h \
    src/threads/userupdate/iuserupdatethread.h \
    src/threads/userupdate/userupdatethread.h \
    src/utils/autorunenabler/autorunenabler.h \
    src/utils/autorunenabler/iautorunenabler.h \
    src/utils/filedialog/filedialog.h \
    src/utils/filedialog/filedialogfactory.h \
    src/utils/filedialog/ifiledialog.h \
    src/utils/filedialog/ifiledialogfactory.h \
    src/utils/fs/dir/dir.h \
    src/utils/fs/dir/dirfactory.h \
    src/utils/fs/dir/idir.h \
    src/utils/fs/dir/idirfactory.h \
    src/utils/fs/file/file.h \
    src/utils/fs/file/filefactory.h \
    src/utils/fs/file/ifile.h \
    src/utils/fs/file/ifilefactory.h \
    src/utils/fs/zip/qzip/iqzip.h \
    src/utils/fs/zip/qzip/iqzipfactory.h \
    src/utils/fs/zip/qzip/qzip.h \
    src/utils/fs/zip/qzip/qzipfactory.h \
    src/utils/fs/zip/qzipfile/iqzipfile.h \
    src/utils/fs/zip/qzipfile/iqzipfilefactory.h \
    src/utils/fs/zip/qzipfile/qzipfile.h \
    src/utils/fs/zip/qzipfile/qzipfilefactory.h \
    src/utils/http/httpclient.h \
    src/utils/http/ihttpclient.h \
    src/utils/logger/logger.h \
    src/utils/messagebox/imessageboxutils.h \
    src/utils/messagebox/messageboxutils.h \
    src/utils/settingseditor/isettingseditor.h \
    src/utils/settingseditor/settingseditor.h \
    src/utils/style/darkpalette.h \
    src/utils/timeutils/itimeutils.h \
    src/utils/timeutils/timeutils.h \
    src/widgets/accountchartwidget/accountchartwidget.h \
    src/widgets/accountchartwidget/accountchartwidgetfactory.h \
    src/widgets/accountchartwidget/charttooltip.h \
    src/widgets/accountchartwidget/iaccountchartwidget.h \
    src/widgets/accountchartwidget/iaccountchartwidgetfactory.h \
    src/widgets/actionstableitemwidget/actionstableitemwidget.h \
    src/widgets/actionstableitemwidget/actionstableitemwidgetfactory.h \
    src/widgets/actionstableitemwidget/iactionstableitemwidget.h \
    src/widgets/actionstableitemwidget/iactionstableitemwidgetfactory.h \
    src/widgets/decisionmakerwidget/decisionmakerwidget.h \
    src/widgets/decisionmakerwidget/decisionmakerwidgetfactory.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidget.h \
    src/widgets/decisionmakerwidget/idecisionmakerwidgetfactory.h \
    src/widgets/logsfilterwidget/ilogsfilterwidget.h \
    src/widgets/logsfilterwidget/ilogsfilterwidgetfactory.h \
    src/widgets/logsfilterwidget/logsfilterwidget.h \
    src/widgets/logsfilterwidget/logsfilterwidgetfactory.h \
    src/widgets/logstablewidget/ilogstablewidget.h \
    src/widgets/logstablewidget/ilogstablewidgetfactory.h \
    src/widgets/logstablewidget/logstablewidget.h \
    src/widgets/logstablewidget/logstablewidgetfactory.h \
    src/widgets/operationstablewidget/ioperationstablewidget.h \
    src/widgets/operationstablewidget/ioperationstablewidgetfactory.h \
    src/widgets/operationstablewidget/operationstablewidget.h \
    src/widgets/operationstablewidget/operationstablewidgetfactory.h \
    src/widgets/orderwaveswidget/iorderwaveswidget.h \
    src/widgets/orderwaveswidget/iorderwaveswidgetfactory.h \
    src/widgets/orderwaveswidget/orderwaveswidget.h \
    src/widgets/orderwaveswidget/orderwaveswidgetfactory.h \
    src/widgets/portfoliotreewidget/iportfoliotreewidget.h \
    src/widgets/portfoliotreewidget/iportfoliotreewidgetfactory.h \
    src/widgets/portfoliotreewidget/portfoliotreewidget.h \
    src/widgets/portfoliotreewidget/portfoliotreewidgetfactory.h \
    src/widgets/stockscontrolswidget/istockscontrolswidget.h \
    src/widgets/stockscontrolswidget/istockscontrolswidgetfactory.h \
    src/widgets/stockscontrolswidget/stockscontrolswidget.h \
    src/widgets/stockscontrolswidget/stockscontrolswidgetfactory.h \
    src/widgets/stockstablewidget/istockstablewidget.h \
    src/widgets/stockstablewidget/istockstablewidgetfactory.h \
    src/widgets/stockstablewidget/stockstablewidget.h \
    src/widgets/stockstablewidget/stockstablewidgetfactory.h \
    src/widgets/tabledelegates/instrumentitemdelegate.h \
    src/widgets/tabledelegates/loglevelitemdelegate.h \
    src/widgets/tablemodels/logstablemodel/comparators.h \
    src/widgets/tablemodels/logstablemodel/ilogstablemodel.h \
    src/widgets/tablemodels/logstablemodel/ilogstablemodelfactory.h \
    src/widgets/tablemodels/logstablemodel/logstablemodel.h \
    src/widgets/tablemodels/logstablemodel/logstablemodelfactory.h \
    src/widgets/tablemodels/modelroles.h \
    src/widgets/tablemodels/operationstablemodel/comparators.h \
    src/widgets/tablemodels/operationstablemodel/ioperationstablemodel.h \
    src/widgets/tablemodels/operationstablemodel/ioperationstablemodelfactory.h \
    src/widgets/tablemodels/operationstablemodel/operationstablemodel.h \
    src/widgets/tablemodels/operationstablemodel/operationstablemodelfactory.h \
    src/widgets/tablemodels/portfoliotreemodel/comparators.h \
    src/widgets/tablemodels/portfoliotreemodel/iportfoliotreemodel.h \
    src/widgets/tablemodels/portfoliotreemodel/iportfoliotreemodelfactory.h \
    src/widgets/tablemodels/portfoliotreemodel/portfoliotreemodel.h \
    src/widgets/tablemodels/portfoliotreemodel/portfoliotreemodelfactory.h \
    src/widgets/tablemodels/stockstablemodel/comparators.h \
    src/widgets/tablemodels/stockstablemodel/istockstablemodel.h \
    src/widgets/tablemodels/stockstablemodel/istockstablemodelfactory.h \
    src/widgets/tablemodels/stockstablemodel/stockstablemodel.h \
    src/widgets/tablemodels/stockstablemodel/stockstablemodelfactory.h \
    src/widgets/trayicon/itrayicon.h \
    src/widgets/trayicon/itrayiconfactory.h \
    src/widgets/trayicon/trayicon.h \
    src/widgets/trayicon/trayiconfactory.h \

# find app/ -name \*.ui | sort | sed "s/app\///g" | sed "s/\.ui/\.ui \\\/g"
FORMS += \
    src/config/decisions/buy/buydecision1config/buydecision1configwidget/buydecision1configwidget.ui \
    src/config/decisions/buy/buydecision2config/buydecision2configwidget/buydecision2configwidget.ui \
    src/config/decisions/buy/buydecision3config/buydecision3configwidget/buydecision3configwidget.ui \
    src/config/decisions/decisionmakerconfigwidget/decisionmakerconfigwidget.ui \
    src/config/decisions/sell/selldecision1config/selldecision1configwidget/selldecision1configwidget.ui \
    src/config/decisions/sell/selldecision2config/selldecision2configwidget/selldecision2configwidget.ui \
    src/config/decisions/sell/selldecision3config/selldecision3configwidget/selldecision3configwidget.ui \
    src/dialogs/authdialog/authdialog.ui \
    src/dialogs/orderwavesdialog/orderwavesdialog.ui \
    src/dialogs/settingsdialog/settingsdialog.ui \
    src/dialogs/startautopilotdialog/startautopilotdialog.ui \
    src/dialogs/startsimulationdialog/startsimulationdialog.ui \
    src/main/mainwindow.ui \
    src/widgets/actionstableitemwidget/actionstableitemwidget.ui \
    src/widgets/decisionmakerwidget/decisionmakerwidget.ui \
    src/widgets/logsfilterwidget/logsfilterwidget.ui \
    src/widgets/logstablewidget/logstablewidget.ui \
    src/widgets/operationstablewidget/operationstablewidget.ui \
    src/widgets/portfoliotreewidget/portfoliotreewidget.ui \
    src/widgets/stockscontrolswidget/stockscontrolswidget.ui \
    src/widgets/stockstablewidget/stockstablewidget.ui \
