name: test-android
description: Test Android
inputs:
  gist-token:
    description: GitHub REST API access token.
    required: true
runs:
  using: "composite"
  steps:
    # Set git to disable line endings conversion
    - name: Configure git
      shell: pwsh
      run: |
        & git config --global core.autocrlf false

    # Checkout latest commit for this repository to $GITHUB_WORKSPACE/TInvestor-source
    - name: Checkout TInvestor
      uses: actions/checkout@v6
      with:
        path: TInvestor-source

    # Calculate TInvestor hash on sources
    - name: Calculate TInvestor hash
      id: folders-hash
      uses: theowenyoung/folder-hash@v3
      with:
        path: |
          ./TInvestor-source/tools/android/notifier

    # Download/upload cache
    - name: Caching
      id: cache-test
      uses: actions/cache@v5
      with:
        path: ./TInvestor-source/tools/android/notifier/app/build/reports
        key: android-test-${{ steps.folders-hash.outputs.hash }}

    # Setup JDK 25
    - name: Setup JDK 25
      if: steps.cache-test.outputs.cache-hit != 'true'
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'gradle'

    # Test UT
    - name: Test UT
      if: steps.cache-test.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-Location -Path "TInvestor-source/tools/android/notifier"
        & sudo timedatectl set-timezone Europe/Moscow

        & ./gradlew verifyRoborazziDebug --stacktrace
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }

        & ./gradlew createUnitTestCoverageReport
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }

        Rename-Item -Path "app/build/reports/coverage/test/debug/report.xml" -NewName "jacoco-report.xml"

    # Upload coverage badge
    - name: Upload coverage badge
      if: steps.cache-test.outputs.cache-hit != 'true'
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ env.GIST_ID }}
        token: ${{ inputs.gist-token }}
        prefix: TInvestor-Android

    # Upload artifacts
    - name: Upload artifacts (roborazzi)
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        name: screenshot-diff-android
        path: ./TInvestor-source/tools/android/notifier/app/build/outputs/roborazzi
        retention-days: 1
        compression-level: 9

    # Upload artifacts
    - name: Upload artifacts (reports)
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        name: coverage-android
        path: ./TInvestor-source/tools/android/notifier/app/build/reports
        retention-days: 1
        compression-level: 9
