name: build-android
description: Build Android
inputs:
  keystore-file:
    description: Keystore file content encoded in base64.
    required: true
  key-alias:
    description: Key alias.
    required: true
  keystore-password:
    description: Keystore password.
    required: true
  key-password:
    description: Key password.
    required: true
runs:
  using: "composite"
  steps:
    # Set git to disable line endings conversion
    - name: Configure git
      shell: pwsh
      run: |
        & git config --global core.autocrlf false

    # Checkout latest commit for this repository to $GITHUB_WORKSPACE/TInvestor-source
    - name: Checkout TInvestor
      uses: actions/checkout@v6
      with:
        path: TInvestor-source

    # Calculate TInvestor hash on sources
    - name: Calculate TInvestor hash
      id: folders-hash
      uses: theowenyoung/folder-hash@v3
      with:
        path: |
          ./TInvestor-source/tools/android/notifier

    # Download/upload cache
    - name: Caching
      id: cache-build
      uses: actions/cache@v5
      with:
        path: ./TInvestor-source/tools/android/notifier/app/build/outputs/apk/release/app-release-unsigned.apk
        key: android-build-${{ steps.folders-hash.outputs.hash }}

    # Setup JDK 25
    - name: Setup JDK 25
      if: steps.cache-build.outputs.cache-hit != 'true'
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'gradle'

    # Build APK
    - name: Build APK
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-Location -Path "TInvestor-source/tools/android/notifier"
        & ./gradlew assembleRelease

    # Prepare Keystore
    - name: Prepare Keystore
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        sudo apt-get update -y
        sudo apt-get install -y coreutils
        mkdir -p /tmp/keystores
        echo "${{ inputs.keystore-file }}" | base64 --decode > /tmp/keystores/keystore.jks

    # Sign APK
    - name: Sign APK
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        & /usr/local/lib/android/sdk/build-tools/36.0.0/apksigner sign --ks /tmp/keystores/keystore.jks --ks-key-alias ${{ inputs.key-alias }} --ks-pass pass:${{ inputs.keystore-password }} --key-pass pass:${{ inputs.key-password }} --out TInvestor-source/tools/android/notifier/app/build/outputs/apk/release/tinvestor-notifier.apk TInvestor-source/tools/android/notifier/app/build/outputs/apk/release/app-release-unsigned.apk

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: build-android
        path: ./TInvestor-source/tools/android/notifier/app/build/outputs/apk/release/tinvestor-notifier.apk
        retention-days: 1
        compression-level: 9
