name: Nightly

on: [push]

# Setup environment variables
env:
  QT_MIRRORS:          "download.qt.io;mirrors.ocf.berkeley.edu/qt;ftp.fau.de/qtproject;mirror.bit.edu.cn/qtproject"
  QT_VERSION:          "6.9.0"
  ZLIB_VERSION:        "v1.3.1"
  QUAZIP_VERSION:      "v1.5"
  VCPKG_VERSION:       "2025.04.09"
  CLANG_VERSION:       "20.1.3"
  GOOGLE_TEST_VERSION: "v1.16.0"

# List of jobs
jobs:
  # Setup environment and upload artifacts
  env-qt-zlib-quazip:
    name: Environment Qt/ZLib/Quazip [${{ matrix.config.name }}]
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "win64", os: windows-latest }
          - { name: "linux", os: ubuntu-latest }
      fail-fast: false

    steps:
      # Checkout latest commit for this repository to $GITHUB_WORKSPACE/TInvestor-actions
      - name: Checkout TInvestor
        uses: actions/checkout@v4
        with:
          path: TInvestor-actions

      # Use local env-qt-zlib-quazip action
      - name: Use local env-qt-zlib-quazip action
        uses: ./TInvestor-actions/.github/actions/env-qt-zlib-quazip

  # Setup environment and upload artifacts
  env-vcpkg:
    name: Environment vcpkg [${{ matrix.config.name }}]
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "win64", os: windows-latest }
          - { name: "linux", os: ubuntu-latest }
      fail-fast: false

    steps:
      # Checkout latest commit for this repository to $GITHUB_WORKSPACE/TInvestor-actions
      - name: Checkout TInvestor
        uses: actions/checkout@v4
        with:
          path: TInvestor-actions

      # Use local env-vcpkg action
      - name: Use local env-vcpkg action
        uses: ./TInvestor-actions/.github/actions/env-vcpkg
