name: Nightly

on: [push]

# Setup environment variables
env:
  QT_MIRRORS:          "download.qt.io;mirrors.ocf.berkeley.edu/qt;ftp.fau.de/qtproject;mirror.bit.edu.cn/qtproject"
  QT_VERSION:          "6.9.0"
  ZLIB_VERSION:        "v1.3.1"
  QUAZIP_VERSION:      "v1.5"
  VCPKG_VERSION:       "2025.04.09"
  CLANG_VERSION:       "20.1.3"
  GOOGLE_TEST_VERSION: "v1.16.0"

# List of jobs
jobs:
  # Setup environment and upload artifacts
  env-qt-zlib-quazip:
    name: Environment Qt/ZLib/Quazip [${{ matrix.config.name }}]
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "win64", os: windows-latest }
          - { name: "linux", os: ubuntu-latest }
      fail-fast: false

    steps:
      # Install required packages
      - name: System packages
        if: steps.cache-env.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          switch ("${{ runner.os }}")
          {
            "Windows" { choco install bzip2 }
            "Linux"   { sudo apt-get update }
            "macOS"   { brew update }
          }
